# Site settings
title: laoYao!!
baseurl: "" # begin with /repo-name if use as project, else leave empty for gh-pages
url: "" # default is empty

# Build settings
kramdown:
  input: GFM
permalink: pretty
